name: Update Primary Color in Another Repository

on:
  workflow_dispatch:  # Trigger the workflow manually

jobs:
  update-primary-color:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Checkout the current repository

    - name: Clone Another Repository
      run: |
        git clone https://github.com/SDC-Louboutin/new-product-api4.git  # Replace with the URL of the repository to update
        cd new-product-api4
        git config user.name "andepants"
        git config user.email "andrewsheim@gmail.com"

    - name: List Files (Debugging)
      run: |
        ls -al   # List files in the current directory for debugging purposes
        cd new-product-api4
        ls -al

    - name: Modify JSON File
      run: |
        # Modify the primary color inside the JSON file using jq
        jq '.colors.primary = "#FF5733"' new-product-api4/color.json > updated-color.json
        mv updated-color.json new-product-api4/color.json

    - name: Commit Changes
      run: |
        git add new-product-api4/color.json
        git commit -m "Update primary color in color.json"

    - name: Push Changes
      run: |
        git push origin main  # Replace 'main' with the target branch of the repository
