name: Update Primary Color in Another Repository

on:
  workflow_dispatch:  # Trigger the workflow manually

jobs:
  update-primary-color:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Checkout the current repository

    - name: Update Submodule
      run: |
        git submodule update --init --recursive
        cd new-product-api4
        git config --global user.name "andepants"
        git config --global user.email "andrewsheim@gmail.com"

    - name: List Files (Debugging)
      run: |
        ls -al   # List files in the current directory for debugging purposes
        cd new-product-api4
        ls -al
        
    - name: View contents of colors.json
      run: cat color.json

    - name: Modify JSON File
      run: |
        # Modify the primary color inside the JSON file using jq
        jq '.colors.primary = "#FF5733"' color.json > updated-color.json
        mv updated-color.json color.json
        git diff
        git status

    - name: View contents of colors.json
      run: cat color.json

    - name: Check Status
      run: |
        git status
        cd ..

    - name: Add Remote for new-product-api4
      run: git remote add origin_repo https://github.com/SDC-Louboutin/new-product-api4.git
      env:
        GH_TOKEN: ${{ secrets.PAT_TOKEN_TO_FORK}}

    - name: Push Changes to origin/main
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        cd new-product-api4
        git add .
        git commit -m "Update primary color in color.json"
        git push origin_repo main
      env:
        GH_TOKEN: ${{ secrets.PAT_TOKEN_TO_FORK}}
        
    - name: Check Status
      run: |
        cd new-product-api4
        git status
