name: Update Primary Color in Another Repository

on:
  workflow_dispatch:  # Trigger the workflow manually

jobs:
  update-primary-color:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Checkout the current repository

    - name: Clone Another Repository
      run: |
        git clone https://github.com/SDC-Louboutin/new-product-api4.git  # Replace with the URL of the repository to update
        cd new-product-api4
        git config --global user.name "andepants"
        git config --global user.email "andrewsheim@gmail.com"

    - name: List Files (Debugging)
      run: |
        ls -al   # List files in the current directory for debugging purposes
        cd new-product-api4
        ls -al
        
    - name: View contents of colors.json
      run: cat new-product-api4/color.json

    - name: Modify JSON File
      run: |
        # Modify the primary color inside the JSON file using jq
        jq '.colors.primary = "#FF5733"' new-product-api4/color.json > updated-color.json
        mv updated-color.json new-product-api4/color.json

    - name: View contents of colors.json
      run: cat new-product-api4/color.json

    - name: Check Status
      run: git status

    - name: Push Changes to origin/main
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git remote add origin_repo https://github.com/SDC-Louboutin/new-product-api4.git  # Replace with your repository URL
        git add new-product-api4/color.json
        git commit -m "Update primary color in color.json"
        git push origin_repo main
      env:
        GH_TOKEN: ${{ secrets.PAT_TOKEN_TO_FORK}}


    - name: Check Status
      run: git status
      
    - name: Commit Changes
      run: |
        git add new-product-api4/color.json
        git commit -m "Update primary color in color.json"

    - name: Push Changes
      run: |
        git push origin main  # Replace 'main' with the target branch of the repository
