name: Update Primary Color in Another Repository

on:
  workflow_dispatch:  # Trigger the workflow manually

jobs:
  update-primary-color:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout new product api repo repo
      uses: actions/checkout@master
      with:
        repository: SDC-Louboutin/new-product-api4
        token: ${{ secrets.PAT_TOKEN_TO_FORK}}

    - name: Set Config
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    - name: List Files (Debugging)
      run: |
        ls -al   # List files in the current directory for debugging purposes
        
    - name: View contents of colors.json
      run: cat color.json
      
    - name: Modify JSON File
      run: |
        # Modify the primary color inside the JSON file using jq
        jq '.colors.primary = "#FF5733"' color.json > updated-color.json
        mv updated-color.json color.json

    - name: View contents of colors.json
      run: cat color.json

    - name: Add, commit, push changes
      run: |
        git status
        git add .
        git commit -m "Update primary color in color.json"
        git push origin main  # Push to the new branch in new-product-api4
        git status
      env:
        GH_TOKEN: ${{ secrets.PAT_TOKEN_TO_FORK}}
      
